"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Room Counter.py']
DATA_FILES = ['--iconfile', './tuned_proper_coco_2.pt']
OPTIONS = {'iconfile': '/Users/ericgu/Documents/backend2020/images/icon.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
